### ISSUE TITLE
Monitoring List for Manage Data API

### ISSUE THREAD

**Issue by ifirmawan** [akvo/rtmis#1166]
Task details: https://app.asana.com/0/1204676393419426/1206532436079139/f

## TODO/DONE

- [x] Backend modifications
- [x] Frontend modifications

### Backend modifications

- [x] Add parent query param
- [x] Add a feature to include the count of children
- [x] Update related tests

### Frontend modifications

- [x] Manage Page
- [x] Monitoring Details page
