### ISSUE TITLE
Manage Claim page and Manage Data changes in Front-end

### ISSUE THREAD

**Issue by ifirmawan** [akvo/rtmis#1313]
## TODO/DONE

- [x] Data claim seeder
- [x] Manage Data (Changes)
- [x] Manage Data Claim (New Feature)
- [x] Modify Demo Approval Workflow CLI

Task details: https://app.asana.com/0/1204676393419426/1206927739070320/f
