### ISSUE TITLE
PowerBI Front-end Implementation 

### ISSUE THREAD

**Issue by ifirmawan** [akvo/rtmis#689]
## TODO/DONE

- [x] Modify config.js to support PowerBI Pages
- [x] Copy PowerBI pages component from NWMIS
- [x] Add route for the PowerBI pages
