### ISSUE TITLE
Modify all the visualisation API

### ISSUE THREAD

**Issue by ifirmawan** [akvo/rtmis#690]
The API should matches new Django Response Grouper API

## TODO/DONE
- [x] Modify map visualisation
- [x] Modify bar chart visualisation
- [x] Modify submission chart
