### ISSUE TITLE
Modify Mobile User Authentication

### ISSUE THREAD

**Issue by ifirmawan** [akvo/rtmis#736]
## TODO/DONE
- [x] Fix Reset / Logout
- [x] Modify Mobile Login and Add User
- [x] Test pushing data-point to Server with Different users token
