### ISSUE TITLE
Test village seeder and check all feature related to this changes

### ISSUE THREAD

**Issue by ifirmawan** [akvo/rtmis#813]
## TODO/DONE

Check affected features :

- [x] Master data Administrations
- [x] Master data Entity data
- [x] Manage Mobile Assignment
